version: 2

aliases:
  - &docker_image ubuntu:bionic
  - &install_common |
      apt-get update -qq
      apt-get install -qq software-properties-common
      add-apt-repository -y ppa:ubuntu-toolchain-r/test
      apt-get update -qq
      apt-get install -qq autoconf automake gcc g++ libboost-dev libgtest-dev libopenmpi-dev libsparsehash-dev make pandoc ssh git

jobs:

  linux_clang6:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq clang-6.0
      - checkout
      - run: |
          ./autogen.sh
          export DISTCHECK_CONFIGURE_FLAGS="CC=clang-6.0 CXX=clang++-6.0"
          ./configure CC=clang-6.0 CXX=clang++-6.0 --with-mpi=/usr/lib/openmpi
      - run: make -j12 distcheck

  linux_gcc5:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq gcc-5 g++-5
      - checkout
      - run: |
          ./autogen.sh
          export DISTCHECK_CONFIGURE_FLAGS="CC=gcc-5 CXX=g++-5"
          ./configure CC=gcc-5 CXX=g++-5 --with-mpi=/usr/lib/openmpi
      - run: make -j12 distcheck

  linux_gcc6:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq gcc-6 g++-6
      - checkout
      - run: |
          ./autogen.sh
          export DISTCHECK_CONFIGURE_FLAGS="CC=gcc-6 CXX=g++-6"
          ./configure CC=gcc-6 CXX=g++-6 --with-mpi=/usr/lib/openmpi
      - run: make -j12 distcheck

  linux_gcc7:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq gcc-7 g++-7
      - checkout
      - run: |
          ./autogen.sh
          export DISTCHECK_CONFIGURE_FLAGS="CC=gcc-7 CXX=g++-7"
          ./configure CC=gcc-7 CXX=g++-7 --with-mpi=/usr/lib/openmpi
      - run: make -j12 distcheck

  linux_gcc8:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install -qq gcc-8 g++-8
      - checkout
      - run: |
          ./autogen.sh
          export DISTCHECK_CONFIGURE_FLAGS="CC=gcc-8 CXX=g++-8"
          ./configure CC=gcc-8 CXX=g++-8 --with-mpi=/usr/lib/openmpi
      - run: make -j12 distcheck

  clang-format:
    docker:
      - image: *docker_image
    steps:
      - run: *install_common
      - run: |
          apt-get install --yes --force-yes sudo
          sudo apt-get install --yes --force-yes curl
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-format-8
          sudo ln -s clang-format-8 /usr/bin/clang-format
      - checkout
      - run: |
          ./autogen.sh
          ./configure
      - run: make clang-format

workflows:
  version: 2
  abyss_builds:
    jobs:
      - linux_gcc8
      - linux_gcc7
      - linux_gcc6
      - linux_gcc5
      - linux_clang6
      - clang-format
